name: Behave Automation Suite CI/CD

on:
  push:
    branches: 
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Install Allure Commandline
      - name: Install Allure Commandline
        run: |
          curl -o allure-commandline.zip -L https://github.com/allure-framework/allure2/releases/download/2.15.0/allure-2.15.0.zip
          unzip allure-commandline.zip -d /opt/allure
          sudo ln -s /opt/allure/allure-2.15.0/bin/allure /usr/local/bin/allure  # Create a symlink to the allure command

      # Step 4: Run Behave tests
      - name: Run Behave tests
        run: |
          behave -f allure_behave.formatter:AllureFormatter -o ./reports